repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    hooks:
      - id: black
        alias: python
        files: ^tubearchivist-metrics/
        args: ["--line-length=120","--diff", "--check"]
  - repo: https://github.com/pycqa/isort
    hooks:
      - id: isort
        name: isort (python)
        alias: python
        files: ^tubearchivist-metrics/
        args: ["--profile", "black", "-l 120"]
  - repo: https://github.com/pycqa/flake8
    hooks:
      - id: flake8
        alias: python
        files: ^tubearchivist-metrics/
        args: ["--max-complexity=10", "--max-line-length=120"]
  - repo: https://github.com/codespell-project/codespell
    hooks:
      - id: codespell
